import { get } from 'jquery';
import {environment} from 'src/environments/environment';

export const API_URL: string = environment.api_url;

export enum ApiMethod {
  GET = "GET",
  POST = "POST",
  PUT = "PUT",
  DELETE = "DELETE",
  PATCH = "PATCH"
}


export const API_ENDPOINTS = {
signIn:'users/login',
registerUser:'users/receptionist',
resetPassword:'users/resetPassword/',
forgetPassword:'users/forgotPassword',
getBrowserDetail:'users/getBrowserDetail/',
setBrowserDetail:'users/setBrowserDetail',
users: 'users',
deleteUser: 'users',
editUser: 'users',
createUser: 'users',
getRoles:'roles',
getRoleByID:'roles/',
createRoles:'roles/createRole',
updateRoles:'roles/updateRole',
deleteRoles:'roles/deleteRole/', 
banners:'banners',
getBannerById:'banners/',
getAllBannersByCompany:'banners/getAllBannersByCompany/',
createBanner:'banners/createBanner',
editBanner:'banners/updateBanner',
deleteBanner:'banners/deleteBanner/',
addVisitor:'visitors', 
addAppointment:'appointments',
getVisitors:'visitors',
getVisitorsById:'visitors/',
updateVisitor:'visitors/updateVisitor/',
deleteVisitors:'visitors/deleteVisitor/',
getAppointments:'appointments',
getAppointmentById:'appointments/',
checkIn:'visitors/checkIn',
checkOut:'visitors/checkOut',
getVisitorDetails:'visitors',
visitorsToday: 'visitors/today',
fetchTasks: 'tasks',
getRate: 'rate',
unattendedVisitors: 'visitors/unattended',
activeSessions: 'sessions/active',
updateUserStatus: 'users/status',
updateUserCheckinStatus: 'users/checkin-status',
updateUser: 'users/updateUser',
addInstitution: 'institutions',
addAdmin: 'users',
getBanks: 'institutuions',
deleteBank: 'institutions/deleteInstitutions',
updateBank: 'banks/updateInstitutuions',
departments: 'departments',
visitorsList: 'visitors',
getUserDetails: 'users',
getInstitutionData: 'institutions',
}
